version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      target: development
    container_name: chat-backend
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/chat-app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data:
